### ISSUE TITLE
Plots in GUI look all the same

### ISSUE THREAD

**Issue by don-i** [neuromti/tool-offspect#51]
Opening a certain ipsi-mapping file (find raw data file on the server: /mnt/data/data08/RawData/2019_ST_IN-TENS/GeKl/post2/mapping_ipsi_R002.xdf) shows only the same plot for all IDs except the last 2 ones.
ID itself is not always the same.
Coordinates also changes.
Seems like there is a bug in the file.

**Comment by don-i** [comment]
Same for another file (find raw data file on the server: /mnt/data/data08/RawData/2019_ST_IN-TENS/GeKl/post4/mapping_ipsi_R005.xdf)

**Comment by don-i** [comment]
same for: /mnt/data/data08/RawData/2019_ST_IN-TENS/GuWi/pre1/mapping_ipsi_R003.xdf
                /mnt/data/data08/RawData/2019_ST_IN-TENS/GuWi/pre1/mapping_ipsi_R004.xdf
(merged to 1 file)
ID´s 57-133 and 134-170

**Comment by agricolab** [comment]
Can you check whether all of this files are merged, i.e. consist of multiple original subfiles? There was a (now fixed) bug (https://github.com/translationalneurosurgery/tool-offspect/issues/46) in the merge function, which could cause traces to be overwritten. That would mean the cachefiles would have to be created again.

**Comment by don-i** [comment]
Only GuWi/pre1 comes from 2 files that are merged. I merged the original subfiles now again but unfortunately the problem still exists.

GeKl/post4, and GeKl/post2 come from single files where I only created the cachefile.

Is there another reason for this issue?

**Comment by don-i** [comment]
same for PlKa/pre4 ipsi data (IDs 1-40, 42-86, 102-163, 165-171(end)).
This file was merged from 3 original subfiles.

**Comment by agricolab** [comment]
Thanks for collecting the offending files, and keep on doing so. I probably won't be able to fix this before my vacation. I'll take a look when i'm back, idealy together with @BettinaTrunk.

**Comment by don-i** [comment]
Don't worry! Thanks in advance and have a nice holiday!
If other files also show this issue, I will keep on leaving comments here!

**Comment by don-i** [comment]
Same for GeKl/post4 (contra)
The plots of traces 1-4, 5-11 and 12-23 look all the same.
The file was created from 3 original subfiles. Converting and merging again was not successful.

**Comment by agricolab** [comment]
Back from vacation, and starting to work on this issue. Thanks for your patience. Can you describe the code or commands you used to create the cachefiles, e.g. for `/mnt/data/data08/RawData/2019_ST_IN-TENS/GeKl/post2/mapping_ipsi_R002.xdf`?

**Comment by don-i** [comment]
For the ipsi-files, I converted every file "by hand" using this command:

`offspect tms -f <my path>\GeKl\mapping_ipsi_R002.xdf -t GeKl_map_ipsilesional_cmep_post2.hdf5 -pp 100 150 -c EDC_L -e localite_marker didt -r cmep`

For the contra files I wrote a short python script and converted the files using the following command:
`populate(cfile, [annotation], [traces])`

**Comment by agricolab** [comment]
`/mnt/data/data08/RawData/2019_ST_IN-TENS/GeKl/post2/mapping_ipsi_R002.xdf` has only 168 seconds of BrainVision Data, and every 8s a `S  2` marker event. There was likely a bug in the recording setup and EEG was not properly recorded.

`/mnt/data/data08/RawData/2019_ST_IN-TENS/GeKl/post4/mapping_ipsi_R005.xdf` has sufficient time, but the 175 `S  2` markers progress backwards in time, and are only 9-16 ms apart. This also seems like a bug in the recording, and the EEG was not properly recorded.

`/mnt/data/data08/RawData/2019_ST_IN-TENS/GuWi/pre1/mapping_ipsi_R003.xdf` and `/mnt/data/data08/RawData/2019_ST_IN-TENS/GuWi/pre1/mapping_ipsi_R004.xdf` recorded two MarkerStreams and two EEG streams. This was likely because LabRecorder recorded these stream from a different experiment running at the same time. Additionally, even in the correct Markerstream, all `S  2` lie within only a single second. There was probably some network hiccup, too.

I am not sure we can salvage the first and second,  but for the GuWi data, we might recover the correct stream.

**Comment by agricolab** [comment]
I could salvage `/mnt/data/data08/RawData/2019_ST_IN-TENS/GeKl/post4/mapping_ipsi_R005.xdf`, `/mnt/data/data08/RawData/2019_ST_IN-TENS/GuWi/pre1/mapping_ipsi_R003.xdf` and `/mnt/data/data08/RawData/2019_ST_IN-TENS/GuWi/pre1/mapping_ipsi_R004.xdf` and send them to you via teams.

`offspect tms -f filename.xdf -t cache.hdf5 -pp 100 150 -c EDC_L -e localite_marker didt -r cmep`  should work on them, too, if you use the newest pyliesl and tool-offspect.

**Comment by agricolab** [comment]
Regarding the contra files, what do you mean with: 
>The file was created from 3 original subfiles. Converting and merging again was not successful.

and can you share the path to the files on the server and your script?

**Comment by don-i** [comment]
I meant that I tried to convert and merge the three subfiles again in case there went something wrong.

I will send you the code via teams!

**Comment by agricolab** [comment]
Scripts look ok, there shouldn't be the fault line.

**Comment by agricolab** [comment]
I lost a little bit the oversight. As it stands, all files but one are now in shipshape. The only offending file is a contra file, right? Can you specify the path to it or share it over teams, and share the path to its origin files (i.e. the xdf-files?)

**Comment by agricolab** [comment]
Thanks for sending over teams. The errors in the offending traces stem from two origin xdfs, which both have timestamp failures and apparently only recorded around 1ms of data. Best to mark these traces as `rejected` and process the remaining ones.
