### ISSUE TITLE
Error when converting two follow-up TMS-Maps

### ISSUE THREAD

**Issue by BettinaTrunk** [neuromti/tool-offspect#53]
Currently, I'm trying to convert Cachefiles from TMS-Maps of the last two follow-up measurements (ZaRo and SaCe). Those were the ones where we had issues with the setup in the TMS room and adapted the code accordingly to get the experiment to run again. By doing that, for example the "reiz_marker_sa" was turned into "reiz-marker" and the maps were not saved in separate "mapping_contra/ipsi_xxxx" files. That's why I tried to convert them using the xdf_specialcases.py script. I created a prepare_annotations_multifile_follow_up which takes "reiz-marker" instead of "reiz_marker_sa". Other than that, it's similar to prepare_annotations_multifile. However, I get the following error and unfortunately don't know how to solve it:

```
Traceback (most recent call last):
  File "mapping_specialcases_follow_up.py", line 52, in <module>
    anno = prepare_annotations_multifile_follow_up(files, origin, filedate, channel, pre_in_ms, post_in_ms)
  File "C:\tool-offspect\offspect\input\tms\cmep\xdf_specialcases.py", line 511, in prepare_annotations_multifile_follow_up
    datastream = pick_stream_with_channel(channel, streams)
  File "C:\tool-offspect\offspect\protocols\xdf.py", line 21, in pick_stream_with_channel
    if stream.channel_labels is not None:
  File "C:\Users\Bettina Trunk\Anaconda3\lib\site-packages\liesl\files\xdf\load.py", line 47, in channel_labels
    return [i["label"] for i in self.desc["channels"]["channel"]]
KeyError: 'channels'
```

The relevant files are: 
/mnt/data/data08/RawData/2019_ST_IN-TENS/SaCe/post5/TMS_NMEs_SaCe_post5.xdf

and 

/mnt/data/data08/RawData/2019_ST_IN-TENS/ZaRo/post5/TMS_NMES_ZaRo_post5.xdf
/mnt/data/data08/RawData/2019_ST_IN-TENS/ZaRo/post5/TMS_NMES_ZaRo_post5_old1.xdf

Do you have an idea what the problem could be?

**Comment by agricolab** [comment]
It seems the respective stream does not contain the information about channel labels as it should. Did we switch EEG setup to eego?

**Comment by BettinaTrunk** [comment]
Ah okay! No, we used the BrainProducts setup as before. 
In this case, I guess I could manually select the respective stream for the two measurements?

**Comment by agricolab** [comment]
Probably, but you would also have to select the channel index for the channel of interest.

**Comment by BettinaTrunk** [comment]
Yes. Thanks! It seems to work.
