### ISSUE TITLE
GUI crashes when I try to open certain files

### ISSUE THREAD

**Issue by don-i** [neuromti/tool-offspect#54]
**Describe the bug**
For some cachefiles (contralateral mappings), the GUI crashes when I try to open those files.

**To Reproduce**
1. Open GUI
2. try to open cachefiles e.g. for MeKu (pre1, contralesional) or PlKa (post3, contralesional)
--> error: `UnboundLocalError: local variable 'idx' referenced before assignment`

**Expected behavior**
Open file without error

**Comment by agricolab** [comment]
Both files consisted of multiple origin files, and some had actually zero traces. You can check for yourself with `offspect peek filename.hdf5`. This caused the function to throw an exception, as we didn't consider this edge case. With the most recent develop tip at https://github.com/translationalneurosurgery/tool-offspect/commit/14ec602241f2e5222d58a136873317d5e4967cda, it should be fixed.

**Comment by don-i** [comment]
Unfortunately, there are two more files where the GUI crashes when opening them:
GuWi/post3, GuWi/post6 (both contralesional)

The following error occurs:
`IndexError: -1 not in cachefile`

Can you help here, too?
Thanks in advance!

**Comment by agricolab** [comment]
Thanks. Both files have zero traces. I added error checks for missing and/or invalid files, and you should starting with https://github.com/translationalneurosurgery/tool-offspect/commit/c6a29356212acf9f75c38b9f2dd93e46b3aa38aa receive informative error message.
